name: I am having difficulty installing Flutter or getting it to work
description: You have run into problems while downloading or installing Flutter, or the
  "flutter" tool is crashing, or you are running into some other issue before even
  being able to use "flutter run".
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using Flutter

        If you are looking for support, please check out our documentation
        or consider asking a question on Stack Overflow:

          - https://flutter.dev/
          - https://api.flutter.dev/
          - https://stackoverflow.com/questions/tagged/flutter?sort=frequent

        If you have found a bug or if our documentation doesn't have an answer
        to what you're looking for, then fill out the template below. Please read
        our guide to filing a bug first: https://flutter.dev/docs/resources/bug-reports
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have read https://flutter.dev/docs/resources/bug-reports
        required: true
      - label: I have searched the existing issues
        required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Please tell us exactly how to reproduce the problem you are running into.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Code sample
      description: Please provide a [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
      render: Dart
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs
      description: |
        Include the full logs of the commands you are running between the lines
        with the backticks below. If you are running any "flutter" commands,
        please include the output of running them with "--verbose"; for example,
        the output of running "flutter --verbose create foo".
      render: console
  - type: textarea
    attributes:
      label: "`flutter doctor -v` output"
      description: |
        Include the entire logs of running `flutter doctor -v`
      render: console
